spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/zuduicom?serverTimezone=UTC&useSSL=false
    driver‐class‐name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML # Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.